blog/config/routes.rb
Blog::Application.routes.draw do
  get "welcome/index"

  get 'tags/:tag', to: 'posts#index', as: :tag

  resources :posts do 
    resources :comments
  end

  root 'welcome#index'
end

blog/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

blog/app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy

  acts_as_taggable

  validates :title, presence: true,
    length: { minimum: 5 }
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  http_basic_authenticate_with name: "kprice", password: "asdf", only: :destroy

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:commenter, :body))
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end
end

blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  http_basic_authenticate_with name: "kprice", password: "asdf", except: [:index, :show]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def show 
    @post = Post.find(params[:id])
  end

  def index
    if params[:tag]
      @posts = Post.tagged_with(params[:tag])
    else
      @posts = Post.all
    end
  end

  def edit 
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(params[:post].permit(:title, :text))
      redirect_to @post
    else 
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :text, :tag_list)
  end
end

blog/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/comments_helper.rb
module CommentsHelper
end

blog/app/helpers/posts_helper.rb
module PostsHelper
end

blog/app/helpers/welcome_helper.rb
module WelcomeHelper
end

blog/app/views/comments/_comment.html.erb
<div class="comment rounded-corners">
    <p>
      <%= comment.commenter %>
      <strong>says</strong>
    </p>

    <p>
      <%= comment.body %>
    </p>

    <p>
    <%= link_to 'Destroy Comment', [comment.post, comment],
      method: :delete,
      data: { confirm: 'Are you sure?' } %>
    </p>
</div>

blog/app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
  <%= f.label :commenter %><br />
  <%= f.text_field :commenter %>
  </p>
  <p>
  <%= f.label :body %><br />
  <%= f.text_area :body %>
  </p>
  <p>
  <%= f.submit %>
  </p>
<% end %>

blog/app/views/layouts/_footer.html.erb
<footer>
  <%= link_to "All", posts_path %> |
  <%= link_to "New", new_post_path %>
</footer>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<%= render "layouts/footer" %>

</body>
</html>

blog/app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div id="errorExplanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
        <% @post.errors.full_messages.each do |mesg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.label :tag_list %><br>
    <%= f.text_field :tag_list %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

blog/app/views/posts/_post.html.erb
<div class='rounded-corners post'>
  <h2><%= post.title %></h2>
  <p><%= post.text %></p>
  <p>tags: <%= raw post.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></p>
  <p>
    <%= link_to 'Show', post_path(post) %> |
    <%= link_to 'Edit', edit_post_path(post) %> |
    <%= link_to 'Destroy', post_path(post), method: :delete, data: { confirm: 'Are you sure?' } %>
  </p>
</div>
      

blog/app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

blog/app/views/posts/index.html.erb
<h1>
  <% if params[:tag] %>
    <%= params[:tag] %>
  <% else %>
    <%= "All Posts" %>
  <% end %>
</h1>

<div id="tag_cloud">
  <% tag_cloud Post.tag_counts, %w{s m l} do |tag, css_class| %>
    <%= link_to tag.name, tag_path(tag.name), class: css_class %>
  <% end %>
</div>

<table>

<% @posts.each do |post| %>
  <tr>
    <td>
      <%= render post %>
    </td>
  </tr>
<% end %>

</table>

blog/app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

blog/app/views/posts/show.html.erb
<table>
  <tr>
    <td>
      <%= render @post %>
    </td>
  </tr>
</table>

<h2>Comments</h2>
<%= render @post.comments %>

<h2>Add a comment:</h2>
<%= render "comments/form" %>

blog/app/views/welcome/index.html.erb
<h1>Hello, World!</h1>